Put react.svg the same place as vite.svg
Because in my built directory, I have build/dist/vite.svg, but
build/dist/assets/react-CHdo91hT.svg. Then in the compiled App.js, I'm
getting an error:

Cannot find module './assets/react.svg'

So I'm doing this to get a file named simply react.svg, instead of
react-...svg.